### ISSUE TITLE
Vitis AI 2.5 Board overload issue

### ISSUE THREAD

**Issue by akshayvignesh** [Xilinx/Vitis-AI#1035]
Hi, 
I tried to execute the Vitis AI 2.5 on U50 lv board. I was able to infer the results for the sample images but when I try to execute the Performance tests my System reboots. What may be the reason for the unexpected reboot? Any leads would be appreciated. 

Command used:

./test_performance_classification resnet50 test_performance_classification.list -t 8 -s 60

System Info:

OS: Ubuntu 18.04.1
kernel: 4.15.0-193-generic
Card :U50LV

**Comment by SuZhan0322** [comment]
Hi @akshayvignesh ,
The System reboots is due to power consumption. And due to power consumption, the alveo card of U50/U50lv needs to be downclocked to 60% to run the model multi-threading test.  Please refer to the command to reduce the frequency: https://docs.xilinx.com/r/2.0-English/ug1354-xilinx-ai-sdk/Scaling-Down-the-Frequency-of-the-DPU
Thanks!

**Comment by SuZhan0322** [comment]
Great! @akshayvignesh I am glad to hear that. And Please reopen the issue if you have any other questions! thanks!
