### ISSUE TITLE
How to evaluate quantized vs floating point YOLOv4?

### ISSUE THREAD

**Issue by vongracia** [Xilinx/Vitis-AI#1064]
Hi,

I'm following this tutorial https://github.com/Xilinx/Vitis-AI-Tutorials/tree/1.4/Design_Tutorials/07-yolov4-tutorial to quantize yolov4 when trained on my custom data.

I can now make inference in my ZCU102, but I'm trying to evaluate floating vs quantized models and don't know how to make adequate changes to tf_eval_yolov4_coco_2017.py to achieve so. This file is coded for the coco dataset, and I'm using a custom dataset. I believe the .py file requires changes to make the evaluation on my custom data.

Can anyone give me a hand?
Thanks

**Comment by vongracia** [comment]
Or at least someone who tells me how to convert my files to coco format to run the script. I see that the .py requires the annotations in .json format. Any help to convert to coco format?

**Comment by wangxd-xlnx** [comment]
Hi @vongracia 

If you need to use your own dataset instead of COCO to evaluate float/quantized model, you could refer to this article. It provided a toolkit that could convert your own annotated data to COCO format. 
https://towardsdatascience.com/how-to-work-with-object-detection-datasets-in-coco-format-9bf4fb5848a4
