### ISSUE TITLE
yolov5 downloaded an empty compressed package

### ISSUE THREAD

**Issue by jia0511** [Xilinx/Vitis-AI#1129]
https://github.com/Xilinx/Vitis-AI/blob/master/model_zoo/model-list/pt_yolov5-large_coco_640_640_109.6G_3.0/model.yaml

**Comment by wangxd-xlnx** [comment]
Hi @jia0511 

Thanks for your feedback. For yolov5/v6 series model, we just provided a README document to share the accuracy and performance instead of the model itself due to limitations of the original model license. 

If you want to get this model, please refer to the contact information in README and contact MKT for further support.

**Comment by jia0511** [comment]
Thank you!
