### ISSUE TITLE
Docker image that contains ONNX quantizer Release Date

### ISSUE THREAD

**Issue by farah-rostom98** [Xilinx/Vitis-AI#1325]
The latest docker image :docker pull xilinx/vitis-ai-cpu:latest  
contained vitis ai v2.5 which doesn't contain ONNX quantizer so when will the docker image that contains ONNX quantizer be released?

**Comment by quentonh** [comment]
@farah-rostom98 vitis-ai-cpu:latest refers to a deprecated container name that was associated with previous releases which incorporated more than one framework into a single container.  Those images are still on Docker Hub but are not updated.  

Vitis AI 3.5 uses a different container naming scheme that is per framework.  See:  https://xilinx.github.io/Vitis-AI/3.5/html/docs/install/install.html#option-1-leverage-the-pre-built-docker.

So for instance:

`./docker_run.sh xilinx/vitis-ai-pytorch-cpu:latest`

Did you find the command "docker pull xilinx/vitis-ai-cpu:latest" in association with documentation for our current release?  If so, please let us know so that we can ensure that this is updated.

**Comment by farah-rostom98** [comment]
My problem is I'd like to use onnx and I don't know which framework supports it?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by quentonh** [comment]
@farah-rostom98 The ONNX Quantizer was introduced in Vitis AI 3.5, so the link that I provided is the correct starting point.

**Comment by quentonh** [comment]
`docker pull vitis-ai-pytorch-cpu:latest`

**Comment by farah-rostom98** [comment]
Thank you so much I’ll hive it a try and get back to you

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by quentonh** [comment]
Sorry, I was distracted by the use of the old container nomenclature.  What you really want, if you want native ONNX Quantization is to follow the separate and distinct steps for that tool.  I would recommend that you start here:  https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/Installing-vai_q_onnx and also here:  https://github.com/Xilinx/Vitis-AI/tree/v3.5/src/vai_quantizer/vai_q_onnx

**Comment by farah-rostom98** [comment]
Thank you so much I’m downloading the PyTorch-cpu latest and I’ll go on from there

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by quentonh** [comment]
FWIW, I just pulled vitis-ai-pytorch-cpu:latest, [built ](https://github.com/Xilinx/Vitis-AI/tree/v3.5/src/vai_quantizer/vai_q_onnx#install-from-source-code-with-wheel-package) the ONNX Quantizer from source, installed the .whl package and was able to run quantization of this [example ](https://github.com/Xilinx/Vitis-AI/tree/v3.5/src/vai_quantizer/vai_q_onnx/example/resnet_ptq_cpu) inside the Pytorch container without any issue.

**Comment by farah-rostom98** [comment]
Hi Quenton,
The quantizer did build and I tried it on the model example but now I have another question.
Is there a onnx compiler ?? Or how am I going to deploy the onnx if there is no compiler ?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by farah-rostom98** [comment]
Thank you so much for your assistance

________________________________
