### ISSUE TITLE
Not able to see the Xilinx board image root folder from Gtkterm

### ISSUE THREAD

**Issue by SusmithaGadagottu** [Xilinx/Vitis-AI#144]
Hi,
I am trying to set up the Xilinx board for testing the Vitis AI 1.2 and currently not able to access the board.

Could you please review the information below and let me know how I can access the board?

As mentioned in the below link that the board image should be 2020.1 I have created the SD card with the latest image which is 2020.1 version
(FileName: xilinx-zcu102-dpu-v2020.1-v1.2.0.img.gz)
https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Library#quick-start-for-edge
With previous versions of the Xilinx board image I was able to access the board using the GtkTerm by configuring the required port information ttyUB0 and BaudRate:115200. This GtkTerm terminal would connect to the board and display the home folder of the Xilinx board image.  I then set the static IP address once on the board and then for future access or to run the tests I used Ethernet connection and SSH access from the host PC to connect to the board and run the tests. 

Looks like this image is different from previous board images, in previous versions of the Xilinx board image, after the Xilinx board is booted I used to see a regular start screen. However this time there is a menu displayed instead of the start screen (I don’t have the screenshot for the previous version of the start screen). Attached is the screenshot that displays the menu directly instead of the start screen with the current version of the board image.
Presently I am not able to access the board at all.

When tried to access using the GtkTerminal, the home folder of the Xilinx board cannot be accessible. The screen stays blank. I tried sending a file to the board form Gtkterm and still nothing happened.
2. I tried connecting the USB mouse to the board, tried with the USB hub and also with the USB30-USB2.0. Still no luck and the mouse is also not working on the board.   

Thanks
Susmitha
![xilinxboardImage](https://user-images.githubusercontent.com/53448224/91582311-7af15a00-e904-11ea-81de-6cfc45f56ebb.jpeg)

**Comment by andrew0917** [comment]
Hi SusmithaGadagottu,
     As for the latest 2020.1 image(FileName: xilinx-zcu102-dpu-v2020.1-v1.2.0.img.gz) in [https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Library#quick-start-for-edge](https://github.com/Xilinx/Vitis-AI/tree/master/Vitis-AI-Library#quick-start-for-edge)

1 . This latest xilinx board image(2020.1 version) is different from previous image, the desktop system is matchbox(a menu displayed that you described )  instead of wayland(a regular start screen that you described).
To reproduce your gtkterm issue, I downloaded and burned this image  into SD card for ZCU102 board.And I found the gtkterm can works well, the specific info as below:

![image](https://user-images.githubusercontent.com/68576025/91835078-7964c080-ec7b-11ea-8795-a0284d3747af.png)

**Note:**
    when you connect the usb-to-serial wire to your computer, there are four serial port in your /dev/ttyUSBxxx,so you should choose the right one. I choose the /dev/ttyUSB0 in my case(/dev/ttyUSB0,/dev/ttyUSB1,/dev/ttyUSB2,/dev/ttyUSB3),it may be diffrent from your environment


2 . I connect the USB mouse and keyboard to the zcu102 board, with the USB hub, and the mouse and keyboard can work well, the specific details as bleow:
![image](https://user-images.githubusercontent.com/68576025/91835387-e5dfbf80-ec7b-11ea-9e24-b85c687d8e81.png)
![image](https://user-images.githubusercontent.com/68576025/91835497-0dcf2300-ec7c-11ea-85b4-69c642e0010c.png)
![image](https://user-images.githubusercontent.com/68576025/91835618-33f4c300-ec7c-11ea-9084-02b7978012bb.png)

**Note:**
    As for your mouse can't work, i only think of the flowing aspects:
   1.  USB physical connetction
   2.  USB hub or mouse is broken
   3.  ZCU102 board jumper settings for Host mode
   J7 - ON
   J113 - 1-2
   J110 - 2-3

Please refer the below image for jumper settings on ZCU102 board
![image](https://user-images.githubusercontent.com/68576025/91836183-03615900-ec7d-11ea-8482-68af23615c11.png)
