### ISSUE TITLE
Invalid Value and Overflows quantization vai-q-pytorch with .pt weights

### ISSUE THREAD

**Issue by Fabioni** [Xilinx/Vitis-AI#471]
Hello,
I get the following output when I quantize a yolov4-csp model using a self trained .pt file for the weights.

![IMG_20210719_185853_891](https://user-images.githubusercontent.com/45362676/126198514-78889c8f-c7c7-490b-8b6a-ca44f1bf4600.jpg)

When I convert the .pt file to darknets .weights file, and then use this everything works fine.
I use https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-csp

Can somebody see what goes wrong here?

Greetings

**Comment by niuxjxlnx** [comment]
Hi, @Fabioni:

Python will do validatoin check of values, these warning of valid value and overflow is correct and useful to help clean up problems in .pt files. It is most likely some parameter values are unreasonable value becaused of not correctly initialized or loaded.

The converted darknet .weights file works fine because of some possible reasons:
1) unreasonable values has been handled to be reasonable during the conversion
2) C/C++ program has less reasonable value check than python

My suggestion is to print the values in .pt files and check why some values cause overflow.

**Comment by Alexiazzf** [comment]
Hi @Fabioni ：

Thank you for your issue. We have added some protections for invalid value and overflows. This bug fix will be open sourced in the next version of vai-q-pytorch.

Best
