### ISSUE TITLE
What is the DPU architecture (eg. B4096?) and configuration (eg. DPU_NUM? URAM? ) in the default ZCU104 board image which you offered in Vitis-AI/setup/mpsoc/VART/ ?

### ISSUE THREAD

**Issue by SuanNaiShuiGuoLao** [Xilinx/Vitis-AI#559]
![image](https://user-images.githubusercontent.com/55835821/137613904-5014bf8b-adc6-4cf2-8e74-b2ce7b41f15c.png)

1. I noticed that the DPU in this board image can process 4 jobs at same time, so I guess the DPU_NUM of the DPU in this image is four. Is this correct? 

2. When customizing a board image with DPU, I noticed that the resources on ZCU104 can not support 4 B4096 DPU cores and can only support 4 smaller cores such as B1600. However, my customized DPU with four B1600 cores is much more slower than the default image you offered in Vitis-AI/setup/mpsoc/VART/. So I am curious what is the exact DPU architecture in your default image? If you used an architecture higher than B1600 (such as B4096), how did you configure the DPU  (eg. DPU_NUM? URAM? ) to make the 4 cores DPU can be deployed with zcu104? Thank you very much.

**Comment by qianglin-xlnx** [comment]
Hi @SuanNaiShuiGuoLao 
Sorry about the late reply.
The DPU core number and arch infor in our released image are shown below:
    ZCU102: 3 x B4096 Core
    ZCU104: 2 x B4096 Core
    KV260  : 1 x B4096 core.
    There is no relationship between the DPU core number and thread number (job).

**Comment by JasonXijieJia** [comment]
Hi @SuanNaiShuiGuoLao 
  The chip zu7 in ZCU104 has less resources than the chip zu9 in ZCU104. 
  And both of them are insufficient to 4 x B4096 cores.  
  You don't have to implement 4x cores if you have 4 tasks to run in parallel. The runtime could handle this with multi-threads and map the multi-tasks to the cores 
  And of course, 4x B1600 must be much slower than 3x B4096, due to not only the peak-compute-power, but also the ddr io bandwidth (aka HP ports)
