### ISSUE TITLE
Problem with .prototxt when deploy on target board

### ISSUE THREAD

**Issue by few22** [Xilinx/Vitis-AI#564]
Hi all,

I trained my custom dataset Yolov4 deploy on a target board , by the way I was follow this tutorial https://github.com/Xilinx/Vitis-AI-Tutorials/tree/master/Design_Tutorials/07-yolov4-tutorial. I was implement by using **tensorflow framework.**

However, For the last step **Model Deployment** my folder contain
├─dpu_yolov4
     --dpu_yolov4.xmodel
     --**dpu_yolov4.prototxt**
     --md5sum.txt
     --meta.json

My custom model was running fine follow this tutorials !

1.)  But I'm just curious that where can I find reference for the information of .prototxt files ?
2.) If I want to change my model to another architecture (yolov3-tiny) How can I modify this .prototxt file ,However I was try it and when the model detect it show the fluctuate bounding boxes and  It cause the mismatch size of bounding boxes

Here is the example of .prototxt files that I'm wondering

![dpu_yolov4](https://user-images.githubusercontent.com/86540413/138023728-ad97f403-a139-4947-a821-dcdb7b0191c8.JPG)

Looking forward for your answer !, Thanks all.

**Comment by jimheaton** [comment]
Your understanding of the conf_threashold is correct. If the prediction score of the object is below this, the the box will not be displayed.

If you use the same image for the host using the floating point model, and then using the quantized model do you see a large difference in the prediction score? If so, it could be due to the INT8 quantizing. What quantization method did you use, and how many calibration images?

**Comment by few22** [comment]
@jimheaton Sorry for late reply sir, My model was totally work fine now !, I think the problem was come from a parameter in my .prototxt file. In this case I did not set a scale to be 1/(input_size) and I was arrange a output layer to be wrong position. So after I fix this It totally work well

Thanks you for clarify sir.
