### ISSUE TITLE
yolov4-tiny  with 7 categories VS  yolov4-tiny with 3 categories

### ISSUE THREAD

**Issue by charles-str** [Xilinx/Vitis-AI#702]
Due to yolov4-tiny CPSdarknet has strided_slice, vitis ai does not support,
I replace strided_slice with 1x1  convolution， but when I train yolov4-tiny with 3 categories, the speed has 30 fps,
yolov4-tiny  with 7 categories has only 3 fps.
this is the netron of with 7 categories.
![7-classess](https://user-images.githubusercontent.com/35334263/157386135-52854bdf-a8b2-41d1-93ed-acd4bb41a69a.png)
this is the netron of with 3 categories.
![3-classess](https://user-images.githubusercontent.com/35334263/157386182-8eabc709-a3f2-4e9e-bf32-456a4053e505.png)

**Comment by charles-str** [comment]
I train yolov4-tiny with darknet

**Comment by tuan3ihust** [comment]
Hello did you solve the problem?
I trained yolov4-tiny with darknet too, and convert to caffe, but the compiled model have multiple DPU subgraph (4), I think it is because vitis ai doesn't support route layer with groups, how do you solve it? did changing it to 1x1 conv reduce model accuracy? thank you.
![image](https://user-images.githubusercontent.com/91899320/204116434-045b93fd-99df-4923-8320-dd9a1f14c1ee.png)
