### ISSUE TITLE
AI-Model-Zoo tensor flow models seem to contain caffe models instead

### ISSUE THREAD

**Issue by JamesCaska** [Xilinx/Vitis-AI#733]
I am new to this but am trying to follow the example for the U250

The example directs me to install the tf_inceptionv1 example

I use the downloader.py which point to

https://www.xilinx.com/bin/public/openDownload?filename=inception_v1_tf-u200-u250-r2.0.0.tar.gz

I was expecting a tf_inceptionv1.pb file but instead it contains

inception_v1_tf.prototxt
inception_v1_tf.xmodel

Which seem to be the same returned by the Caffe version.

This seems true for other tf models and also historically in previous repos. 

So possibly I misunderstand what's supposed to be in this model archive or your build tools are copying over the Caffe models into the tensoflow models.

Needless to say this is very confusing when trying orientate a first example

**Comment by woinck** [comment]
Hello @JamesCaska , the .xmodel in `inception_v1_tf-u200-u250-r2.0.0.tar.gz` is a compiled model  for u200-u250 target. The `tf_` means the model is originally from a tensorflow model. Also, the prototxt file is not a prototxt for caffe models. It's used for some of the vitis-ai-library examples. If you just want to run U250 examples, you can just ignore them. 

If you just want to get the tensorflow format of the model (`.pb` file), please choose `GPU` instead of U250 when using downloader.py and check the `float` subdirectory in the zip file.
