### ISSUE TITLE
Does vitis-AI1.4 the official image for zcu102 support direct connection to DisplayPort to achieve image and video classification and detection results? How can I display the results?

### ISSUE THREAD

**Issue by LoeWHJ** [Xilinx/Vitis-AI#773]

**Comment by zz002** [comment]
hi @LoeWHJ 
You can use the USB micro-AB connector to connect a mouse and keyboard to the ZCU102, and use DisplayPort to connect a monitor.
Write a program like [demo](https://github.com/Xilinx/Vitis-AI/blob/1.4/tools/Vitis-AI-Runtime/VART/vart/dpu-runner/samples/adas_detection/src/main.cc#L178), and then run it in the system of zcu102, instead of running it through remote login
       cv::imshow("ADAS Detection@Xilinx DPU", frame);

**Comment by qianglin-xlnx** [comment]
Hi @LoeWHJ 
Has this issue been solved?

**Comment by qianglin-xlnx** [comment]
Hi @LoeWHJ 
Since we haven't received your reply for a long time, we assume you have solved this issue and I'm going to close it. If you still have any questions, please feel free to reopen it. Thank you very much.
