### ISSUE TITLE
WeGo torchscript model

### ISSUE THREAD

**Issue by mehdi-nait** [Xilinx/Vitis-AI#927]
Is there any documentation on how to use WeGo, I'm having trouble loading the quantized model, and in the examples there's no indication as to the model extension to be used (is it the generated .xmodel or a torch.jit.save of the quantized model ?)

**Comment by Mookel** [comment]
Hi, @mehdi-nait , sorry for the late reply.

Regarding PyTorch, WeGO will accept a quantized model with TorchScript format traced by Vitis-AI pytorch quantizer through a new extend API which has not yet been documented in the UG since wego-torch is just an EA version. If you want to export a torchscript module, you can use following API of the vitis-ai pytorch quantizer:

`def export_traced_torch_script(self, output_dir="quantize_result", verbose=False)`

This API’s usage is similar to this one: https://docs.xilinx.com/r/en-US/ug1414-vitis-ai/def-export_xmodel-self-output_dir-deploy_check 

Please contact us if you have any questions.
